# Task 1: Data Cleaning & Preprocessing
Dataset: Titanic Dataset

Objective: Clean and prepare raw data for analysis

Tasks:
- Handle missing values
- Remove duplicates
- Convert data types
- Rename columns

Output: Clean dataset ready for analysis

## Required Imports for the Project

In [27]:
# imports
import pandas as pd
import os

In [28]:
# import the dataset from kaggle
# dataset URL -> https://www.kaggle.com/datasets/ahmadshogran/the-titanic
import kagglehub
path = kagglehub.dataset_download("ahmadshogran/the-titanic")

Using Colab cache for faster access to the 'the-titanic' dataset.

## Loading the Dataset

### Dataset Description

- **Total Passengers:** 891
- **Features:** 12 (including target `Survived`)
- **Target Variable:** `Survived` (0 = No, 1 = Yes)
- **Key Features:** Passenger class (`Pclass`), Sex, Age, Fare, Cabin, Embarked
- **Missing Data:** Present in `Age`, `Cabin`, and `Embarked`

In [29]:
# Load the Titanic dataset
print(os.listdir(path))
data = pd.read_csv(path + '/titanic.csv')
display(data)

['titanic.csv']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [40]:
data.columns

Index(['Passenger_Id', 'Survived', 'P_Class', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [39]:
data.shape

(891, 11)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Passenger_Id  891 non-null    int64
 1   Survived      891 non-null    bool
 2   P_Class       891 non-null    category
 3   Name          891 non-null    object
 4   Sex           891 non-null    object
 5   Age           891 non-null    int64
 6   SibSp         891 non-null    int64
 7   Parch         891 non-null    int64
 8   Ticket        891 non-null    object
 9   Fare          891 non-null    float64
 10  Embarked      891 non-null    category
dtypes: bool(1), category(2), float64(1), int64(4), object(3)
memory usage: 58.7+ KB

## Handle Missing Values

In [30]:
# find the number of NaNs in the dataset
num_nans = data.isna().sum().sum()
print(f'Number of missing values in the dataset: {num_nans}')

# find the columns that contains the NaNs
col_nan = data.isna().sum()
display(col_nan)

Number of missing values in the dataset: 866

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [31]:
# Handle missing values in 'Age' with median
data['Age'] = data['Age'].fillna(data['Age'].median())

# Fill missing 'Embarked' with mode
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

# Drop 'Cabin' because it has a lot of NaN values
data = data.drop('Cabin', axis= 1)

# Display the cleaned DataFrame without missing values
display(data)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [32]:
# Check the results after handling missing values
num_nans = data.isna().sum().sum()
print(f'Number of missing values in the dataset: {num_nans}')

Number of missing values in the dataset: 0

## Remove Duplicates

In [33]:
# Remove Duplicates
# Find the number of duplicates in the dataset and print it
duplicates = data.duplicated().sum()
print(f'Number of Duplicates before removing it -> {duplicates}')

# Remove duplicates
data = data.drop_duplicates(keep='first')

# Display the DataFrame
print('Dataset after removing Duplicated rows:')
display(data)

Number of Duplicates before removing it -> 0
Dataset after removing Duplicated rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

## Convert data types

In [34]:
# display the datatype for each column
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [35]:
# Convert some data types for some columns
data['Survived'] = data['Survived'].astype('bool')
data['Pclass'] = data['Pclass'].astype('category')
data['Sex'] = data['Sex'].astype('category')
data['Embarked'] = data['Embarked'].astype('category')
data['Age'] = data['Age'].astype('int64')

# Standardize values and ensure correct data types
# standardize Sex to lowercase 'male'/'female' and format Fare to two decimal places.
data['Sex'] = data['Sex'].str.lower()
data['Fare'] = data['Fare'].round(2).astype(float)
display(data)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.28,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.92,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.10,S
4,5,False,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.00,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.00,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28,1,2,W./C. 6607,23.45,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.00,C
890,891,False,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,Q

## Rename columns

In [36]:
# renaming for some columns in the dataset
data.rename(columns={'PassengerId':'Passenger_Id', 'Pclass':'P_Class', 'SipSp': 'Sibling_Num'}, inplace=True)
display(data)

,Passenger_Id,Survived,P_Class,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,False,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.28,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.92,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.10,S
4,5,False,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.00,S
887,888,True,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.00,S
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28,1,2,W./C. 6607,23.45,S
889,890,True,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.00,C
890,891,False,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,Q

## Save Cleaned Dataset

In [37]:
#save the final cleaned dataset
data.to_csv("titanic_cleaned.csv", index=False)
print("\n'titanic_cleaned.csv' Saved")

'titanic_cleaned.csv' Saved

## Summary of Data Cleaning & Preprocessing

- **Missing Values Handled:**
  - `Age`: Filled with median
  - `Embarked`: Filled with mode
  - `Cabin`: Dropped entirely

- **Duplicates Removed:** 0 duplicate rows found

- **Data Types Converted:**
  - `Survived` → boolean
  - `Pclass` → category
  - `Sex` → category
  - `Embarked` → category
  - `Age` → integer
  - `Fare` → float (rounded to 2 decimals)

- **Columns Renamed:**
  - `PassengerId` → `Passenger_Id`
  - `Pclass` → `P_Class`

- **Final Dataset Shape:** 891 rows × 11 columns

- **Missing Values After Cleaning:** 0

**Cleaned dataset saved as:** `titanic_cleaned.csv`